/**
 * Built-in themes: blocks of overrides for the color variables in
 * styles/tokens.css (the theme API). Themes touch colors only — fonts,
 * sizes and spacing stay with the token layer.
 *
 * Palettes follow their upstream schemes (nord.com, gruvbox, and the
 * omarchy default set); shades the schemes don't define (dim/faint text,
 * accent tints) are hand-derived to match the Solarized Light defaults'
 * roles.
 */

export const THEME_COLOR_VARS = [
  "--bg",
  "--bg-alt",
  "--bg-raised",
  "--fg",
  "--fg-bright",
  "--fg-dim",
  "--fg-faint",
  "--accent",
  "--accent-dim",
  "--accent-bg",
  "--overlay",
  "--border",
  "--border-focus",
  "--block-1",
  "--block-2",
  "--block-3",
  "--block-4",
  "--ok",
  "--warn",
  "--err",
] as const;

export type ThemeColorVar = (typeof THEME_COLOR_VARS)[number];
export type ThemeVars = Partial<Record<ThemeColorVar, string>>;

export interface BuiltinTheme {
  id: string;
  label: string;
  vars: ThemeVars;
}

export const BUILTIN_THEMES: BuiltinTheme[] = [
  // The default: tokens.css itself, so it overrides nothing.
  { id: "solarized-light", label: "solarized light", vars: {} },
  {
    id: "nord",
    label: "nord",
    vars: {
      "--bg": "#2e3440",
      "--bg-alt": "#3b4252",
      "--bg-raised": "#434c5e",
      "--fg": "#d8dee9",
      "--fg-bright": "#eceff4",
      "--fg-dim": "#97a1b6",
      "--fg-faint": "#616e88",
      "--accent": "#88c0d0",
      "--accent-dim": "#5b7a88",
      "--accent-bg": "#455764",
      "--overlay": "rgb(0 0 0 / 0.5)",
      "--border": "#4c566a",
      "--border-focus": "var(--accent)",
      "--block-1": "#b48ead",
      "--block-2": "#8fbcbb",
      "--block-3": "#d08770",
      "--block-4": "#ebcb8b",
      "--ok": "#a3be8c",
      "--warn": "#ebcb8b",
      "--err": "#bf616a",
    },
  },
  {
    id: "gruvbox-dark",
    label: "gruvbox dark",
    vars: {
      "--bg": "#282828",
      "--bg-alt": "#3c3836",
      "--bg-raised": "#504945",
      "--fg": "#ebdbb2",
      "--fg-bright": "#fbf1c7",
      "--fg-dim": "#a89984",
      "--fg-faint": "#7c6f64",
      "--accent": "#fe8019",
      "--accent-dim": "#935421",
      "--accent-bg": "#5d3e24",
      "--overlay": "rgb(0 0 0 / 0.5)",
      "--border": "#665c54",
      "--border-focus": "var(--accent)",
      "--block-1": "#d3869b",
      "--block-2": "#8ec07c",
      "--block-3": "#83a598",
      "--block-4": "#fabd2f",
      "--ok": "#b8bb26",
      "--warn": "#fabd2f",
      "--err": "#fb4934",
    },
  },
  {
    id: "tokyo-night",
    label: "tokyo night",
    vars: {
      "--bg": "#1a1b26",
      "--bg-alt": "#1f2335",
      "--bg-raised": "#292e42",
      "--fg": "#a9b1d6",
      "--fg-bright": "#c0caf5",
      "--fg-dim": "#565f89",
      "--fg-faint": "#414868",
      "--accent": "#7aa2f7",
      "--accent-dim": "#4a5f8e",
      "--accent-bg": "#323c5a",
      "--overlay": "rgb(0 0 0 / 0.5)",
      "--border": "#3b4261",
      "--border-focus": "var(--accent)",
      "--block-1": "#bb9af7",
      "--block-2": "#7dcfff",
      "--block-3": "#ff9e64",
      "--block-4": "#e0af68",
      "--ok": "#9ece6a",
      "--warn": "#e0af68",
      "--err": "#f7768e",
    },
  },
  {
    id: "catppuccin",
    label: "catppuccin",
    vars: {
      "--bg": "#1e1e2e",
      "--bg-alt": "#313244",
      "--bg-raised": "#45475a",
      "--fg": "#cdd6f4",
      "--fg-bright": "#e2e8fa",
      "--fg-dim": "#a6adc8",
      "--fg-faint": "#6c7086",
      "--accent": "#cba6f7",
      "--accent-dim": "#746292",
      "--accent-bg": "#494060",
      "--overlay": "rgb(0 0 0 / 0.5)",
      "--border": "#585b70",
      "--border-focus": "var(--accent)",
      "--block-1": "#b4befe",
      "--block-2": "#94e2d5",
      "--block-3": "#f5c2e7",
      "--block-4": "#f9e2af",
      "--ok": "#a6e3a1",
      "--warn": "#f9e2af",
      "--err": "#f38ba8",
    },
  },
  {
    id: "catppuccin-latte",
    label: "catppuccin latte",
    vars: {
      "--bg": "#eff1f5",
      "--bg-alt": "#e6e9ef",
      "--bg-raised": "#ccd0da",
      "--fg": "#4c4f69",
      "--fg-bright": "#2f3247",
      "--fg-dim": "#8c8fa1",
      "--fg-faint": "#9ca0b0",
      "--accent": "#8839ef",
      "--accent-dim": "#bb95f2",
      "--accent-bg": "#d5c3f4",
      "--overlay": "rgb(76 79 105 / 0.4)",
      "--border": "#bcc0cc",
      "--border-focus": "var(--accent)",
      "--block-1": "#7287fd",
      "--block-2": "#179299",
      "--block-3": "#ea76cb",
      "--block-4": "#df8e1d",
      "--ok": "#40a02b",
      "--warn": "#df8e1d",
      "--err": "#d20f39",
    },
  },
  {
    id: "everforest",
    label: "everforest",
    vars: {
      "--bg": "#2d353b",
      "--bg-alt": "#343f44",
      "--bg-raised": "#3d484d",
      "--fg": "#d3c6aa",
      "--fg-bright": "#e9e0c9",
      "--fg-dim": "#859289",
      "--fg-faint": "#7a8478",
      "--accent": "#a7c080",
      "--accent-dim": "#6a7a5d",
      "--accent-bg": "#4b574c",
      "--overlay": "rgb(0 0 0 / 0.5)",
      "--border": "#475258",
      "--border-focus": "var(--accent)",
      "--block-1": "#d699b6",
      "--block-2": "#83c092",
      "--block-3": "#7fbbb3",
      "--block-4": "#dbbc7f",
      "--ok": "#a7c080",
      "--warn": "#dbbc7f",
      "--err": "#e67e80",
    },
  },
  {
    id: "kanagawa",
    label: "kanagawa",
    vars: {
      "--bg": "#1f1f28",
      "--bg-alt": "#2a2a37",
      "--bg-raised": "#363646",
      "--fg": "#dcd7ba",
      "--fg-bright": "#ece6c8",
      "--fg-dim": "#727169",
      "--fg-faint": "#54546d",
      "--accent": "#7e9cd8",
      "--accent-dim": "#4e5d80",
      "--accent-bg": "#363e54",
      "--overlay": "rgb(0 0 0 / 0.5)",
      "--border": "#54546d",
      "--border-focus": "var(--accent)",
      "--block-1": "#957fb8",
      "--block-2": "#7aa89f",
      "--block-3": "#d27e99",
      "--block-4": "#e6c384",
      "--ok": "#98bb6c",
      "--warn": "#e6c384",
      "--err": "#e82424",
    },
  },
  {
    id: "matte-black",
    label: "matte black",
    vars: {
      "--bg": "#121212",
      "--bg-alt": "#1c1c1c",
      "--bg-raised": "#282828",
      "--fg": "#bebebe",
      "--fg-bright": "#eaeaea",
      "--fg-dim": "#8a8a8a",
      "--fg-faint": "#5a5a5a",
      "--accent": "#c8a15a",
      "--accent-dim": "#6d5936",
      "--accent-bg": "#3a3324",
      "--overlay": "rgb(0 0 0 / 0.6)",
      "--border": "#333333",
      "--border-focus": "var(--accent)",
      "--block-1": "#a08fb8",
      "--block-2": "#7fa8a3",
      "--block-3": "#b8848f",
      "--block-4": "#b0a26e",
      "--ok": "#8aa87f",
      "--warn": "#c8a15a",
      "--err": "#b85c5c",
    },
  },
  {
    id: "osaka-jade",
    label: "osaka jade",
    vars: {
      "--bg": "#111c18",
      "--bg-alt": "#17251f",
      "--bg-raised": "#1f312a",
      "--fg": "#c1d9cd",
      "--fg-bright": "#e6f2ec",
      "--fg-dim": "#7d9c8d",
      "--fg-faint": "#4f6a5d",
      "--accent": "#5fc79a",
      "--accent-dim": "#387159",
      "--accent-bg": "#244638",
      "--overlay": "rgb(0 0 0 / 0.55)",
      "--border": "#2b463a",
      "--border-focus": "var(--accent)",
      "--block-1": "#9aa3d0",
      "--block-2": "#6ac3cd",
      "--block-3": "#c983ab",
      "--block-4": "#c9bd83",
      "--ok": "#7fc983",
      "--warn": "#c9b16a",
      "--err": "#c96a6a",
    },
  },
  {
    id: "ristretto",
    label: "ristretto",
    vars: {
      "--bg": "#2c2525",
      "--bg-alt": "#403838",
      "--bg-raised": "#5b5353",
      "--fg": "#e3d7d9",
      "--fg-bright": "#fff1f3",
      "--fg-dim": "#c3b7b8",
      "--fg-faint": "#72696a",
      "--accent": "#f38d70",
      "--accent-dim": "#90594b",
      "--accent-bg": "#5d3f38",
      "--overlay": "rgb(0 0 0 / 0.5)",
      "--border": "#5b5353",
      "--border-focus": "var(--accent)",
      "--block-1": "#a8a9eb",
      "--block-2": "#85dacc",
      "--block-3": "#fd6883",
      "--block-4": "#f9cc6c",
      "--ok": "#adda78",
      "--warn": "#f9cc6c",
      "--err": "#fd6883",
    },
  },
  {
    id: "rose-pine",
    label: "rose pine",
    vars: {
      "--bg": "#191724",
      "--bg-alt": "#1f1d2e",
      "--bg-raised": "#26233a",
      "--fg": "#e0def4",
      "--fg-bright": "#f4f2ff",
      "--fg-dim": "#908caa",
      "--fg-faint": "#6e6a86",
      "--accent": "#ebbcba",
      "--accent-dim": "#82696f",
      "--accent-bg": "#4d4049",
      "--overlay": "rgb(0 0 0 / 0.5)",
      "--border": "#403d52",
      "--border-focus": "var(--accent)",
      "--block-1": "#c4a7e7",
      "--block-2": "#9ccfd8",
      "--block-3": "#eb6f92",
      "--block-4": "#f6c177",
      "--ok": "#9ccfd8",
      "--warn": "#f6c177",
      "--err": "#eb6f92",
    },
  },
];
